project_name: dateparse
builds:
  -
    id: "dateparse"
    binary: "dateparse"
    dir: dateparse
  -
    id: "example"
    binary: "example"
    dir: example
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
